version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_bd
    restart: always
    env_file:
      - .env
    ports:
      - "5430:5432"  # host:container (corrigido aqui também)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: